services:
  nats:
    image: nats:latest
    container_name: nats-oms
    command: "-js -m 8222"
    ports:
      - "4222:4222"
      - "8222:8222"
      - "6222:6222"
    volumes:
      - nats-data:/data
    networks:
      - oms-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8222/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3

  vault:
    image: hashicorp/vault:latest
    container_name: vault-oms
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root-token
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    ports:
      - "8200:8200"
    volumes:
      - vault-data:/vault/data
    networks:
      - oms-network
    restart: unless-stopped

volumes:
  nats-data:
  vault-data:

networks:
  oms-network:
    driver: bridge