// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.6.1
// source: oms/v1/auth.proto

package omsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Permission levels
type Permission int32

const (
	Permission_PERMISSION_UNSPECIFIED      Permission = 0
	Permission_PERMISSION_READ_ORDERS      Permission = 1
	Permission_PERMISSION_WRITE_ORDERS     Permission = 2
	Permission_PERMISSION_READ_POSITIONS   Permission = 3
	Permission_PERMISSION_READ_MARKET_DATA Permission = 4
	Permission_PERMISSION_ADMIN            Permission = 100
)

// Enum value maps for Permission.
var (
	Permission_name = map[int32]string{
		0:   "PERMISSION_UNSPECIFIED",
		1:   "PERMISSION_READ_ORDERS",
		2:   "PERMISSION_WRITE_ORDERS",
		3:   "PERMISSION_READ_POSITIONS",
		4:   "PERMISSION_READ_MARKET_DATA",
		100: "PERMISSION_ADMIN",
	}
	Permission_value = map[string]int32{
		"PERMISSION_UNSPECIFIED":      0,
		"PERMISSION_READ_ORDERS":      1,
		"PERMISSION_WRITE_ORDERS":     2,
		"PERMISSION_READ_POSITIONS":   3,
		"PERMISSION_READ_MARKET_DATA": 4,
		"PERMISSION_ADMIN":            100,
	}
)

func (x Permission) Enum() *Permission {
	p := new(Permission)
	*p = x
	return p
}

func (x Permission) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Permission) Descriptor() protoreflect.EnumDescriptor {
	return file_oms_v1_auth_proto_enumTypes[0].Descriptor()
}

func (Permission) Type() protoreflect.EnumType {
	return &file_oms_v1_auth_proto_enumTypes[0]
}

func (x Permission) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Permission.Descriptor instead.
func (Permission) EnumDescriptor() ([]byte, []int) {
	return file_oms_v1_auth_proto_rawDescGZIP(), []int{0}
}

// AuthRequest for API authentication
type AuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	Secret        string                 `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	Totp          string                 `protobuf:"bytes,3,opt,name=totp,proto3" json:"totp,omitempty"` // Optional 2FA code
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthRequest) Reset() {
	*x = AuthRequest{}
	mi := &file_oms_v1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRequest) ProtoMessage() {}

func (x *AuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oms_v1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRequest.ProtoReflect.Descriptor instead.
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return file_oms_v1_auth_proto_rawDescGZIP(), []int{0}
}

func (x *AuthRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *AuthRequest) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *AuthRequest) GetTotp() string {
	if x != nil {
		return x.Totp
	}
	return ""
}

// AuthResponse contains authentication token
type AuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	ExpiresAt     *Timestamp             `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Permissions   []string               `protobuf:"bytes,3,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthResponse) Reset() {
	*x = AuthResponse{}
	mi := &file_oms_v1_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResponse) ProtoMessage() {}

func (x *AuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_oms_v1_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResponse.ProtoReflect.Descriptor instead.
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return file_oms_v1_auth_proto_rawDescGZIP(), []int{1}
}

func (x *AuthResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AuthResponse) GetExpiresAt() *Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *AuthResponse) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

// RefreshTokenRequest for refreshing authentication
type RefreshTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenRequest) Reset() {
	*x = RefreshTokenRequest{}
	mi := &file_oms_v1_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenRequest) ProtoMessage() {}

func (x *RefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oms_v1_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_oms_v1_auth_proto_rawDescGZIP(), []int{2}
}

func (x *RefreshTokenRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

// RefreshTokenResponse contains new tokens
type RefreshTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	ExpiresAt     *Timestamp             `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenResponse) Reset() {
	*x = RefreshTokenResponse{}
	mi := &file_oms_v1_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenResponse) ProtoMessage() {}

func (x *RefreshTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_oms_v1_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenResponse.ProtoReflect.Descriptor instead.
func (*RefreshTokenResponse) Descriptor() ([]byte, []int) {
	return file_oms_v1_auth_proto_rawDescGZIP(), []int{3}
}

func (x *RefreshTokenResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *RefreshTokenResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *RefreshTokenResponse) GetExpiresAt() *Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

// API key management
type APIKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Permissions   []Permission           `protobuf:"varint,3,rep,packed,name=permissions,proto3,enum=oms.v1.Permission" json:"permissions,omitempty"`
	CreatedAt     *Timestamp             `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastUsed      *Timestamp             `protobuf:"bytes,5,opt,name=last_used,json=lastUsed,proto3" json:"last_used,omitempty"`
	IsActive      bool                   `protobuf:"varint,6,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APIKey) Reset() {
	*x = APIKey{}
	mi := &file_oms_v1_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIKey) ProtoMessage() {}

func (x *APIKey) ProtoReflect() protoreflect.Message {
	mi := &file_oms_v1_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIKey.ProtoReflect.Descriptor instead.
func (*APIKey) Descriptor() ([]byte, []int) {
	return file_oms_v1_auth_proto_rawDescGZIP(), []int{4}
}

func (x *APIKey) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *APIKey) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *APIKey) GetPermissions() []Permission {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *APIKey) GetCreatedAt() *Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *APIKey) GetLastUsed() *Timestamp {
	if x != nil {
		return x.LastUsed
	}
	return nil
}

func (x *APIKey) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

// CreateAPIKeyRequest
type CreateAPIKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Permissions   []Permission           `protobuf:"varint,2,rep,packed,name=permissions,proto3,enum=oms.v1.Permission" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAPIKeyRequest) Reset() {
	*x = CreateAPIKeyRequest{}
	mi := &file_oms_v1_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAPIKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAPIKeyRequest) ProtoMessage() {}

func (x *CreateAPIKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oms_v1_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAPIKeyRequest.ProtoReflect.Descriptor instead.
func (*CreateAPIKeyRequest) Descriptor() ([]byte, []int) {
	return file_oms_v1_auth_proto_rawDescGZIP(), []int{5}
}

func (x *CreateAPIKeyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateAPIKeyRequest) GetPermissions() []Permission {
	if x != nil {
		return x.Permissions
	}
	return nil
}

// CreateAPIKeyResponse
type CreateAPIKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        *APIKey                `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	Secret        string                 `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"` // Only returned once
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAPIKeyResponse) Reset() {
	*x = CreateAPIKeyResponse{}
	mi := &file_oms_v1_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAPIKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAPIKeyResponse) ProtoMessage() {}

func (x *CreateAPIKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_oms_v1_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAPIKeyResponse.ProtoReflect.Descriptor instead.
func (*CreateAPIKeyResponse) Descriptor() ([]byte, []int) {
	return file_oms_v1_auth_proto_rawDescGZIP(), []int{6}
}

func (x *CreateAPIKeyResponse) GetApiKey() *APIKey {
	if x != nil {
		return x.ApiKey
	}
	return nil
}

func (x *CreateAPIKeyResponse) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

// ListAPIKeysRequest
type ListAPIKeysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAPIKeysRequest) Reset() {
	*x = ListAPIKeysRequest{}
	mi := &file_oms_v1_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAPIKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAPIKeysRequest) ProtoMessage() {}

func (x *ListAPIKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oms_v1_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAPIKeysRequest.ProtoReflect.Descriptor instead.
func (*ListAPIKeysRequest) Descriptor() ([]byte, []int) {
	return file_oms_v1_auth_proto_rawDescGZIP(), []int{7}
}

// ListAPIKeysResponse
type ListAPIKeysResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKeys       []*APIKey              `protobuf:"bytes,1,rep,name=api_keys,json=apiKeys,proto3" json:"api_keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAPIKeysResponse) Reset() {
	*x = ListAPIKeysResponse{}
	mi := &file_oms_v1_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAPIKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAPIKeysResponse) ProtoMessage() {}

func (x *ListAPIKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_oms_v1_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAPIKeysResponse.ProtoReflect.Descriptor instead.
func (*ListAPIKeysResponse) Descriptor() ([]byte, []int) {
	return file_oms_v1_auth_proto_rawDescGZIP(), []int{8}
}

func (x *ListAPIKeysResponse) GetApiKeys() []*APIKey {
	if x != nil {
		return x.ApiKeys
	}
	return nil
}

// RevokeAPIKeyRequest
type RevokeAPIKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKeyId      string                 `protobuf:"bytes,1,opt,name=api_key_id,json=apiKeyId,proto3" json:"api_key_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeAPIKeyRequest) Reset() {
	*x = RevokeAPIKeyRequest{}
	mi := &file_oms_v1_auth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeAPIKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeAPIKeyRequest) ProtoMessage() {}

func (x *RevokeAPIKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oms_v1_auth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeAPIKeyRequest.ProtoReflect.Descriptor instead.
func (*RevokeAPIKeyRequest) Descriptor() ([]byte, []int) {
	return file_oms_v1_auth_proto_rawDescGZIP(), []int{9}
}

func (x *RevokeAPIKeyRequest) GetApiKeyId() string {
	if x != nil {
		return x.ApiKeyId
	}
	return ""
}

// RevokeAPIKeyResponse
type RevokeAPIKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeAPIKeyResponse) Reset() {
	*x = RevokeAPIKeyResponse{}
	mi := &file_oms_v1_auth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeAPIKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeAPIKeyResponse) ProtoMessage() {}

func (x *RevokeAPIKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_oms_v1_auth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeAPIKeyResponse.ProtoReflect.Descriptor instead.
func (*RevokeAPIKeyResponse) Descriptor() ([]byte, []int) {
	return file_oms_v1_auth_proto_rawDescGZIP(), []int{10}
}

func (x *RevokeAPIKeyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_oms_v1_auth_proto protoreflect.FileDescriptor

const file_oms_v1_auth_proto_rawDesc = "" +
	"\n" +
	"\x11oms/v1/auth.proto\x12\x06oms.v1\x1a\x13oms/v1/common.proto\"R\n" +
	"\vAuthRequest\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\x12\x16\n" +
	"\x06secret\x18\x02 \x01(\tR\x06secret\x12\x12\n" +
	"\x04totp\x18\x03 \x01(\tR\x04totp\"x\n" +
	"\fAuthResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x120\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\v2\x11.oms.v1.TimestampR\texpiresAt\x12 \n" +
	"\vpermissions\x18\x03 \x03(\tR\vpermissions\":\n" +
	"\x13RefreshTokenRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"\x90\x01\n" +
	"\x14RefreshTokenResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x120\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\v2\x11.oms.v1.TimestampR\texpiresAt\"\xe1\x01\n" +
	"\x06APIKey\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x124\n" +
	"\vpermissions\x18\x03 \x03(\x0e2\x12.oms.v1.PermissionR\vpermissions\x120\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x11.oms.v1.TimestampR\tcreatedAt\x12.\n" +
	"\tlast_used\x18\x05 \x01(\v2\x11.oms.v1.TimestampR\blastUsed\x12\x1b\n" +
	"\tis_active\x18\x06 \x01(\bR\bisActive\"_\n" +
	"\x13CreateAPIKeyRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x124\n" +
	"\vpermissions\x18\x02 \x03(\x0e2\x12.oms.v1.PermissionR\vpermissions\"W\n" +
	"\x14CreateAPIKeyResponse\x12'\n" +
	"\aapi_key\x18\x01 \x01(\v2\x0e.oms.v1.APIKeyR\x06apiKey\x12\x16\n" +
	"\x06secret\x18\x02 \x01(\tR\x06secret\"\x14\n" +
	"\x12ListAPIKeysRequest\"@\n" +
	"\x13ListAPIKeysResponse\x12)\n" +
	"\bapi_keys\x18\x01 \x03(\v2\x0e.oms.v1.APIKeyR\aapiKeys\"3\n" +
	"\x13RevokeAPIKeyRequest\x12\x1c\n" +
	"\n" +
	"api_key_id\x18\x01 \x01(\tR\bapiKeyId\"0\n" +
	"\x14RevokeAPIKeyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess*\xb7\x01\n" +
	"\n" +
	"Permission\x12\x1a\n" +
	"\x16PERMISSION_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16PERMISSION_READ_ORDERS\x10\x01\x12\x1b\n" +
	"\x17PERMISSION_WRITE_ORDERS\x10\x02\x12\x1d\n" +
	"\x19PERMISSION_READ_POSITIONS\x10\x03\x12\x1f\n" +
	"\x1bPERMISSION_READ_MARKET_DATA\x10\x04\x12\x14\n" +
	"\x10PERMISSION_ADMIN\x10dB.Z,github.com/mExOms/oms/pkg/proto/oms/v1;omsv1b\x06proto3"

var (
	file_oms_v1_auth_proto_rawDescOnce sync.Once
	file_oms_v1_auth_proto_rawDescData []byte
)

func file_oms_v1_auth_proto_rawDescGZIP() []byte {
	file_oms_v1_auth_proto_rawDescOnce.Do(func() {
		file_oms_v1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_oms_v1_auth_proto_rawDesc), len(file_oms_v1_auth_proto_rawDesc)))
	})
	return file_oms_v1_auth_proto_rawDescData
}

var file_oms_v1_auth_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_oms_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_oms_v1_auth_proto_goTypes = []any{
	(Permission)(0),              // 0: oms.v1.Permission
	(*AuthRequest)(nil),          // 1: oms.v1.AuthRequest
	(*AuthResponse)(nil),         // 2: oms.v1.AuthResponse
	(*RefreshTokenRequest)(nil),  // 3: oms.v1.RefreshTokenRequest
	(*RefreshTokenResponse)(nil), // 4: oms.v1.RefreshTokenResponse
	(*APIKey)(nil),               // 5: oms.v1.APIKey
	(*CreateAPIKeyRequest)(nil),  // 6: oms.v1.CreateAPIKeyRequest
	(*CreateAPIKeyResponse)(nil), // 7: oms.v1.CreateAPIKeyResponse
	(*ListAPIKeysRequest)(nil),   // 8: oms.v1.ListAPIKeysRequest
	(*ListAPIKeysResponse)(nil),  // 9: oms.v1.ListAPIKeysResponse
	(*RevokeAPIKeyRequest)(nil),  // 10: oms.v1.RevokeAPIKeyRequest
	(*RevokeAPIKeyResponse)(nil), // 11: oms.v1.RevokeAPIKeyResponse
	(*Timestamp)(nil),            // 12: oms.v1.Timestamp
}
var file_oms_v1_auth_proto_depIdxs = []int32{
	12, // 0: oms.v1.AuthResponse.expires_at:type_name -> oms.v1.Timestamp
	12, // 1: oms.v1.RefreshTokenResponse.expires_at:type_name -> oms.v1.Timestamp
	0,  // 2: oms.v1.APIKey.permissions:type_name -> oms.v1.Permission
	12, // 3: oms.v1.APIKey.created_at:type_name -> oms.v1.Timestamp
	12, // 4: oms.v1.APIKey.last_used:type_name -> oms.v1.Timestamp
	0,  // 5: oms.v1.CreateAPIKeyRequest.permissions:type_name -> oms.v1.Permission
	5,  // 6: oms.v1.CreateAPIKeyResponse.api_key:type_name -> oms.v1.APIKey
	5,  // 7: oms.v1.ListAPIKeysResponse.api_keys:type_name -> oms.v1.APIKey
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_oms_v1_auth_proto_init() }
func file_oms_v1_auth_proto_init() {
	if File_oms_v1_auth_proto != nil {
		return
	}
	file_oms_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_oms_v1_auth_proto_rawDesc), len(file_oms_v1_auth_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_oms_v1_auth_proto_goTypes,
		DependencyIndexes: file_oms_v1_auth_proto_depIdxs,
		EnumInfos:         file_oms_v1_auth_proto_enumTypes,
		MessageInfos:      file_oms_v1_auth_proto_msgTypes,
	}.Build()
	File_oms_v1_auth_proto = out.File
	file_oms_v1_auth_proto_goTypes = nil
	file_oms_v1_auth_proto_depIdxs = nil
}
