// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.6.1
// source: oms/v1/common.proto

package omsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// OrderSide represents the side of an order
type OrderSide int32

const (
	OrderSide_ORDER_SIDE_UNSPECIFIED OrderSide = 0
	OrderSide_ORDER_SIDE_BUY         OrderSide = 1
	OrderSide_ORDER_SIDE_SELL        OrderSide = 2
)

// Enum value maps for OrderSide.
var (
	OrderSide_name = map[int32]string{
		0: "ORDER_SIDE_UNSPECIFIED",
		1: "ORDER_SIDE_BUY",
		2: "ORDER_SIDE_SELL",
	}
	OrderSide_value = map[string]int32{
		"ORDER_SIDE_UNSPECIFIED": 0,
		"ORDER_SIDE_BUY":         1,
		"ORDER_SIDE_SELL":        2,
	}
)

func (x OrderSide) Enum() *OrderSide {
	p := new(OrderSide)
	*p = x
	return p
}

func (x OrderSide) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderSide) Descriptor() protoreflect.EnumDescriptor {
	return file_oms_v1_common_proto_enumTypes[0].Descriptor()
}

func (OrderSide) Type() protoreflect.EnumType {
	return &file_oms_v1_common_proto_enumTypes[0]
}

func (x OrderSide) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderSide.Descriptor instead.
func (OrderSide) EnumDescriptor() ([]byte, []int) {
	return file_oms_v1_common_proto_rawDescGZIP(), []int{0}
}

// OrderType represents the type of an order
type OrderType int32

const (
	OrderType_ORDER_TYPE_UNSPECIFIED       OrderType = 0
	OrderType_ORDER_TYPE_MARKET            OrderType = 1
	OrderType_ORDER_TYPE_LIMIT             OrderType = 2
	OrderType_ORDER_TYPE_STOP_LOSS         OrderType = 3
	OrderType_ORDER_TYPE_STOP_LOSS_LIMIT   OrderType = 4
	OrderType_ORDER_TYPE_TAKE_PROFIT       OrderType = 5
	OrderType_ORDER_TYPE_TAKE_PROFIT_LIMIT OrderType = 6
	OrderType_ORDER_TYPE_LIMIT_MAKER       OrderType = 7
)

// Enum value maps for OrderType.
var (
	OrderType_name = map[int32]string{
		0: "ORDER_TYPE_UNSPECIFIED",
		1: "ORDER_TYPE_MARKET",
		2: "ORDER_TYPE_LIMIT",
		3: "ORDER_TYPE_STOP_LOSS",
		4: "ORDER_TYPE_STOP_LOSS_LIMIT",
		5: "ORDER_TYPE_TAKE_PROFIT",
		6: "ORDER_TYPE_TAKE_PROFIT_LIMIT",
		7: "ORDER_TYPE_LIMIT_MAKER",
	}
	OrderType_value = map[string]int32{
		"ORDER_TYPE_UNSPECIFIED":       0,
		"ORDER_TYPE_MARKET":            1,
		"ORDER_TYPE_LIMIT":             2,
		"ORDER_TYPE_STOP_LOSS":         3,
		"ORDER_TYPE_STOP_LOSS_LIMIT":   4,
		"ORDER_TYPE_TAKE_PROFIT":       5,
		"ORDER_TYPE_TAKE_PROFIT_LIMIT": 6,
		"ORDER_TYPE_LIMIT_MAKER":       7,
	}
)

func (x OrderType) Enum() *OrderType {
	p := new(OrderType)
	*p = x
	return p
}

func (x OrderType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderType) Descriptor() protoreflect.EnumDescriptor {
	return file_oms_v1_common_proto_enumTypes[1].Descriptor()
}

func (OrderType) Type() protoreflect.EnumType {
	return &file_oms_v1_common_proto_enumTypes[1]
}

func (x OrderType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderType.Descriptor instead.
func (OrderType) EnumDescriptor() ([]byte, []int) {
	return file_oms_v1_common_proto_rawDescGZIP(), []int{1}
}

// OrderStatus represents the status of an order
type OrderStatus int32

const (
	OrderStatus_ORDER_STATUS_UNSPECIFIED      OrderStatus = 0
	OrderStatus_ORDER_STATUS_NEW              OrderStatus = 1
	OrderStatus_ORDER_STATUS_PARTIALLY_FILLED OrderStatus = 2
	OrderStatus_ORDER_STATUS_FILLED           OrderStatus = 3
	OrderStatus_ORDER_STATUS_CANCELED         OrderStatus = 4
	OrderStatus_ORDER_STATUS_PENDING_CANCEL   OrderStatus = 5
	OrderStatus_ORDER_STATUS_REJECTED         OrderStatus = 6
	OrderStatus_ORDER_STATUS_EXPIRED          OrderStatus = 7
)

// Enum value maps for OrderStatus.
var (
	OrderStatus_name = map[int32]string{
		0: "ORDER_STATUS_UNSPECIFIED",
		1: "ORDER_STATUS_NEW",
		2: "ORDER_STATUS_PARTIALLY_FILLED",
		3: "ORDER_STATUS_FILLED",
		4: "ORDER_STATUS_CANCELED",
		5: "ORDER_STATUS_PENDING_CANCEL",
		6: "ORDER_STATUS_REJECTED",
		7: "ORDER_STATUS_EXPIRED",
	}
	OrderStatus_value = map[string]int32{
		"ORDER_STATUS_UNSPECIFIED":      0,
		"ORDER_STATUS_NEW":              1,
		"ORDER_STATUS_PARTIALLY_FILLED": 2,
		"ORDER_STATUS_FILLED":           3,
		"ORDER_STATUS_CANCELED":         4,
		"ORDER_STATUS_PENDING_CANCEL":   5,
		"ORDER_STATUS_REJECTED":         6,
		"ORDER_STATUS_EXPIRED":          7,
	}
)

func (x OrderStatus) Enum() *OrderStatus {
	p := new(OrderStatus)
	*p = x
	return p
}

func (x OrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_oms_v1_common_proto_enumTypes[2].Descriptor()
}

func (OrderStatus) Type() protoreflect.EnumType {
	return &file_oms_v1_common_proto_enumTypes[2]
}

func (x OrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderStatus.Descriptor instead.
func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return file_oms_v1_common_proto_rawDescGZIP(), []int{2}
}

// TimeInForce represents how long an order will remain active
type TimeInForce int32

const (
	TimeInForce_TIME_IN_FORCE_UNSPECIFIED TimeInForce = 0
	TimeInForce_TIME_IN_FORCE_GTC         TimeInForce = 1 // Good Till Cancel
	TimeInForce_TIME_IN_FORCE_IOC         TimeInForce = 2 // Immediate or Cancel
	TimeInForce_TIME_IN_FORCE_FOK         TimeInForce = 3 // Fill or Kill
	TimeInForce_TIME_IN_FORCE_GTX         TimeInForce = 4 // Good Till Crossing (Post Only)
)

// Enum value maps for TimeInForce.
var (
	TimeInForce_name = map[int32]string{
		0: "TIME_IN_FORCE_UNSPECIFIED",
		1: "TIME_IN_FORCE_GTC",
		2: "TIME_IN_FORCE_IOC",
		3: "TIME_IN_FORCE_FOK",
		4: "TIME_IN_FORCE_GTX",
	}
	TimeInForce_value = map[string]int32{
		"TIME_IN_FORCE_UNSPECIFIED": 0,
		"TIME_IN_FORCE_GTC":         1,
		"TIME_IN_FORCE_IOC":         2,
		"TIME_IN_FORCE_FOK":         3,
		"TIME_IN_FORCE_GTX":         4,
	}
)

func (x TimeInForce) Enum() *TimeInForce {
	p := new(TimeInForce)
	*p = x
	return p
}

func (x TimeInForce) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TimeInForce) Descriptor() protoreflect.EnumDescriptor {
	return file_oms_v1_common_proto_enumTypes[3].Descriptor()
}

func (TimeInForce) Type() protoreflect.EnumType {
	return &file_oms_v1_common_proto_enumTypes[3]
}

func (x TimeInForce) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TimeInForce.Descriptor instead.
func (TimeInForce) EnumDescriptor() ([]byte, []int) {
	return file_oms_v1_common_proto_rawDescGZIP(), []int{3}
}

// Market type
type Market int32

const (
	Market_MARKET_UNSPECIFIED Market = 0
	Market_MARKET_SPOT        Market = 1
	Market_MARKET_FUTURES     Market = 2
)

// Enum value maps for Market.
var (
	Market_name = map[int32]string{
		0: "MARKET_UNSPECIFIED",
		1: "MARKET_SPOT",
		2: "MARKET_FUTURES",
	}
	Market_value = map[string]int32{
		"MARKET_UNSPECIFIED": 0,
		"MARKET_SPOT":        1,
		"MARKET_FUTURES":     2,
	}
)

func (x Market) Enum() *Market {
	p := new(Market)
	*p = x
	return p
}

func (x Market) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Market) Descriptor() protoreflect.EnumDescriptor {
	return file_oms_v1_common_proto_enumTypes[4].Descriptor()
}

func (Market) Type() protoreflect.EnumType {
	return &file_oms_v1_common_proto_enumTypes[4]
}

func (x Market) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Market.Descriptor instead.
func (Market) EnumDescriptor() ([]byte, []int) {
	return file_oms_v1_common_proto_rawDescGZIP(), []int{4}
}

// Timestamp message
type Timestamp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seconds       int64                  `protobuf:"varint,1,opt,name=seconds,proto3" json:"seconds,omitempty"`
	Nanos         int32                  `protobuf:"varint,2,opt,name=nanos,proto3" json:"nanos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Timestamp) Reset() {
	*x = Timestamp{}
	mi := &file_oms_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Timestamp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Timestamp) ProtoMessage() {}

func (x *Timestamp) ProtoReflect() protoreflect.Message {
	mi := &file_oms_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Timestamp.ProtoReflect.Descriptor instead.
func (*Timestamp) Descriptor() ([]byte, []int) {
	return file_oms_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *Timestamp) GetSeconds() int64 {
	if x != nil {
		return x.Seconds
	}
	return 0
}

func (x *Timestamp) GetNanos() int32 {
	if x != nil {
		return x.Nanos
	}
	return 0
}

// Decimal represents a decimal number
type Decimal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"` // String representation to avoid precision loss
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Decimal) Reset() {
	*x = Decimal{}
	mi := &file_oms_v1_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Decimal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Decimal) ProtoMessage() {}

func (x *Decimal) ProtoReflect() protoreflect.Message {
	mi := &file_oms_v1_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Decimal.ProtoReflect.Descriptor instead.
func (*Decimal) Descriptor() ([]byte, []int) {
	return file_oms_v1_common_proto_rawDescGZIP(), []int{1}
}

func (x *Decimal) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// PriceLevel represents a price level in the order book
type PriceLevel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Price         *Decimal               `protobuf:"bytes,1,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      *Decimal               `protobuf:"bytes,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PriceLevel) Reset() {
	*x = PriceLevel{}
	mi := &file_oms_v1_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriceLevel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceLevel) ProtoMessage() {}

func (x *PriceLevel) ProtoReflect() protoreflect.Message {
	mi := &file_oms_v1_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceLevel.ProtoReflect.Descriptor instead.
func (*PriceLevel) Descriptor() ([]byte, []int) {
	return file_oms_v1_common_proto_rawDescGZIP(), []int{2}
}

func (x *PriceLevel) GetPrice() *Decimal {
	if x != nil {
		return x.Price
	}
	return nil
}

func (x *PriceLevel) GetQuantity() *Decimal {
	if x != nil {
		return x.Quantity
	}
	return nil
}

var File_oms_v1_common_proto protoreflect.FileDescriptor

const file_oms_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x13oms/v1/common.proto\x12\x06oms.v1\";\n" +
	"\tTimestamp\x12\x18\n" +
	"\aseconds\x18\x01 \x01(\x03R\aseconds\x12\x14\n" +
	"\x05nanos\x18\x02 \x01(\x05R\x05nanos\"\x1f\n" +
	"\aDecimal\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"`\n" +
	"\n" +
	"PriceLevel\x12%\n" +
	"\x05price\x18\x01 \x01(\v2\x0f.oms.v1.DecimalR\x05price\x12+\n" +
	"\bquantity\x18\x02 \x01(\v2\x0f.oms.v1.DecimalR\bquantity*P\n" +
	"\tOrderSide\x12\x1a\n" +
	"\x16ORDER_SIDE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eORDER_SIDE_BUY\x10\x01\x12\x13\n" +
	"\x0fORDER_SIDE_SELL\x10\x02*\xe8\x01\n" +
	"\tOrderType\x12\x1a\n" +
	"\x16ORDER_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11ORDER_TYPE_MARKET\x10\x01\x12\x14\n" +
	"\x10ORDER_TYPE_LIMIT\x10\x02\x12\x18\n" +
	"\x14ORDER_TYPE_STOP_LOSS\x10\x03\x12\x1e\n" +
	"\x1aORDER_TYPE_STOP_LOSS_LIMIT\x10\x04\x12\x1a\n" +
	"\x16ORDER_TYPE_TAKE_PROFIT\x10\x05\x12 \n" +
	"\x1cORDER_TYPE_TAKE_PROFIT_LIMIT\x10\x06\x12\x1a\n" +
	"\x16ORDER_TYPE_LIMIT_MAKER\x10\a*\xee\x01\n" +
	"\vOrderStatus\x12\x1c\n" +
	"\x18ORDER_STATUS_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10ORDER_STATUS_NEW\x10\x01\x12!\n" +
	"\x1dORDER_STATUS_PARTIALLY_FILLED\x10\x02\x12\x17\n" +
	"\x13ORDER_STATUS_FILLED\x10\x03\x12\x19\n" +
	"\x15ORDER_STATUS_CANCELED\x10\x04\x12\x1f\n" +
	"\x1bORDER_STATUS_PENDING_CANCEL\x10\x05\x12\x19\n" +
	"\x15ORDER_STATUS_REJECTED\x10\x06\x12\x18\n" +
	"\x14ORDER_STATUS_EXPIRED\x10\a*\x88\x01\n" +
	"\vTimeInForce\x12\x1d\n" +
	"\x19TIME_IN_FORCE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11TIME_IN_FORCE_GTC\x10\x01\x12\x15\n" +
	"\x11TIME_IN_FORCE_IOC\x10\x02\x12\x15\n" +
	"\x11TIME_IN_FORCE_FOK\x10\x03\x12\x15\n" +
	"\x11TIME_IN_FORCE_GTX\x10\x04*E\n" +
	"\x06Market\x12\x16\n" +
	"\x12MARKET_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vMARKET_SPOT\x10\x01\x12\x12\n" +
	"\x0eMARKET_FUTURES\x10\x02B.Z,github.com/mExOms/pkg/proto/oms/v1;omsv1b\x06proto3"

var (
	file_oms_v1_common_proto_rawDescOnce sync.Once
	file_oms_v1_common_proto_rawDescData []byte
)

func file_oms_v1_common_proto_rawDescGZIP() []byte {
	file_oms_v1_common_proto_rawDescOnce.Do(func() {
		file_oms_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_oms_v1_common_proto_rawDesc), len(file_oms_v1_common_proto_rawDesc)))
	})
	return file_oms_v1_common_proto_rawDescData
}

var file_oms_v1_common_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_oms_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_oms_v1_common_proto_goTypes = []any{
	(OrderSide)(0),     // 0: oms.v1.OrderSide
	(OrderType)(0),     // 1: oms.v1.OrderType
	(OrderStatus)(0),   // 2: oms.v1.OrderStatus
	(TimeInForce)(0),   // 3: oms.v1.TimeInForce
	(Market)(0),        // 4: oms.v1.Market
	(*Timestamp)(nil),  // 5: oms.v1.Timestamp
	(*Decimal)(nil),    // 6: oms.v1.Decimal
	(*PriceLevel)(nil), // 7: oms.v1.PriceLevel
}
var file_oms_v1_common_proto_depIdxs = []int32{
	6, // 0: oms.v1.PriceLevel.price:type_name -> oms.v1.Decimal
	6, // 1: oms.v1.PriceLevel.quantity:type_name -> oms.v1.Decimal
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_oms_v1_common_proto_init() }
func file_oms_v1_common_proto_init() {
	if File_oms_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_oms_v1_common_proto_rawDesc), len(file_oms_v1_common_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_oms_v1_common_proto_goTypes,
		DependencyIndexes: file_oms_v1_common_proto_depIdxs,
		EnumInfos:         file_oms_v1_common_proto_enumTypes,
		MessageInfos:      file_oms_v1_common_proto_msgTypes,
	}.Build()
	File_oms_v1_common_proto = out.File
	file_oms_v1_common_proto_goTypes = nil
	file_oms_v1_common_proto_depIdxs = nil
}
