// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.6.1
// source: oms/v1/order.proto

package omsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Order represents a trading order
type Order struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ClientOrderId    string                 `protobuf:"bytes,2,opt,name=client_order_id,json=clientOrderId,proto3" json:"client_order_id,omitempty"`
	Exchange         string                 `protobuf:"bytes,3,opt,name=exchange,proto3" json:"exchange,omitempty"`
	Symbol           string                 `protobuf:"bytes,4,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Side             OrderSide              `protobuf:"varint,5,opt,name=side,proto3,enum=oms.v1.OrderSide" json:"side,omitempty"`
	Type             OrderType              `protobuf:"varint,6,opt,name=type,proto3,enum=oms.v1.OrderType" json:"type,omitempty"`
	Price            *Decimal               `protobuf:"bytes,7,opt,name=price,proto3" json:"price,omitempty"`
	Quantity         *Decimal               `protobuf:"bytes,8,opt,name=quantity,proto3" json:"quantity,omitempty"`
	ExecutedQuantity *Decimal               `protobuf:"bytes,9,opt,name=executed_quantity,json=executedQuantity,proto3" json:"executed_quantity,omitempty"`
	Status           OrderStatus            `protobuf:"varint,10,opt,name=status,proto3,enum=oms.v1.OrderStatus" json:"status,omitempty"`
	TimeInForce      TimeInForce            `protobuf:"varint,11,opt,name=time_in_force,json=timeInForce,proto3,enum=oms.v1.TimeInForce" json:"time_in_force,omitempty"`
	Market           Market                 `protobuf:"varint,12,opt,name=market,proto3,enum=oms.v1.Market" json:"market,omitempty"`
	CreatedAt        *Timestamp             `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        *Timestamp             `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Additional fields for advanced orders
	StopPrice     *Decimal `protobuf:"bytes,15,opt,name=stop_price,json=stopPrice,proto3" json:"stop_price,omitempty"`
	ReduceOnly    bool     `protobuf:"varint,16,opt,name=reduce_only,json=reduceOnly,proto3" json:"reduce_only,omitempty"`
	PostOnly      bool     `protobuf:"varint,17,opt,name=post_only,json=postOnly,proto3" json:"post_only,omitempty"`
	PositionSide  string   `protobuf:"bytes,18,opt,name=position_side,json=positionSide,proto3" json:"position_side,omitempty"` // For futures: LONG, SHORT, BOTH
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_oms_v1_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_oms_v1_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_oms_v1_order_proto_rawDescGZIP(), []int{0}
}

func (x *Order) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Order) GetClientOrderId() string {
	if x != nil {
		return x.ClientOrderId
	}
	return ""
}

func (x *Order) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *Order) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Order) GetSide() OrderSide {
	if x != nil {
		return x.Side
	}
	return OrderSide_ORDER_SIDE_UNSPECIFIED
}

func (x *Order) GetType() OrderType {
	if x != nil {
		return x.Type
	}
	return OrderType_ORDER_TYPE_UNSPECIFIED
}

func (x *Order) GetPrice() *Decimal {
	if x != nil {
		return x.Price
	}
	return nil
}

func (x *Order) GetQuantity() *Decimal {
	if x != nil {
		return x.Quantity
	}
	return nil
}

func (x *Order) GetExecutedQuantity() *Decimal {
	if x != nil {
		return x.ExecutedQuantity
	}
	return nil
}

func (x *Order) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_ORDER_STATUS_UNSPECIFIED
}

func (x *Order) GetTimeInForce() TimeInForce {
	if x != nil {
		return x.TimeInForce
	}
	return TimeInForce_TIME_IN_FORCE_UNSPECIFIED
}

func (x *Order) GetMarket() Market {
	if x != nil {
		return x.Market
	}
	return Market_MARKET_UNSPECIFIED
}

func (x *Order) GetCreatedAt() *Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Order) GetUpdatedAt() *Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Order) GetStopPrice() *Decimal {
	if x != nil {
		return x.StopPrice
	}
	return nil
}

func (x *Order) GetReduceOnly() bool {
	if x != nil {
		return x.ReduceOnly
	}
	return false
}

func (x *Order) GetPostOnly() bool {
	if x != nil {
		return x.PostOnly
	}
	return false
}

func (x *Order) GetPositionSide() string {
	if x != nil {
		return x.PositionSide
	}
	return ""
}

// OrderRequest for creating new orders
type OrderRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Exchange    string                 `protobuf:"bytes,1,opt,name=exchange,proto3" json:"exchange,omitempty"`
	Symbol      string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Side        OrderSide              `protobuf:"varint,3,opt,name=side,proto3,enum=oms.v1.OrderSide" json:"side,omitempty"`
	Type        OrderType              `protobuf:"varint,4,opt,name=type,proto3,enum=oms.v1.OrderType" json:"type,omitempty"`
	Price       *Decimal               `protobuf:"bytes,5,opt,name=price,proto3" json:"price,omitempty"`
	Quantity    *Decimal               `protobuf:"bytes,6,opt,name=quantity,proto3" json:"quantity,omitempty"`
	TimeInForce TimeInForce            `protobuf:"varint,7,opt,name=time_in_force,json=timeInForce,proto3,enum=oms.v1.TimeInForce" json:"time_in_force,omitempty"`
	Market      Market                 `protobuf:"varint,8,opt,name=market,proto3,enum=oms.v1.Market" json:"market,omitempty"`
	// Optional fields
	ClientOrderId string   `protobuf:"bytes,9,opt,name=client_order_id,json=clientOrderId,proto3" json:"client_order_id,omitempty"`
	StopPrice     *Decimal `protobuf:"bytes,10,opt,name=stop_price,json=stopPrice,proto3" json:"stop_price,omitempty"`
	ReduceOnly    bool     `protobuf:"varint,11,opt,name=reduce_only,json=reduceOnly,proto3" json:"reduce_only,omitempty"`
	PostOnly      bool     `protobuf:"varint,12,opt,name=post_only,json=postOnly,proto3" json:"post_only,omitempty"`
	PositionSide  string   `protobuf:"bytes,13,opt,name=position_side,json=positionSide,proto3" json:"position_side,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderRequest) Reset() {
	*x = OrderRequest{}
	mi := &file_oms_v1_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderRequest) ProtoMessage() {}

func (x *OrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oms_v1_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderRequest.ProtoReflect.Descriptor instead.
func (*OrderRequest) Descriptor() ([]byte, []int) {
	return file_oms_v1_order_proto_rawDescGZIP(), []int{1}
}

func (x *OrderRequest) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *OrderRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *OrderRequest) GetSide() OrderSide {
	if x != nil {
		return x.Side
	}
	return OrderSide_ORDER_SIDE_UNSPECIFIED
}

func (x *OrderRequest) GetType() OrderType {
	if x != nil {
		return x.Type
	}
	return OrderType_ORDER_TYPE_UNSPECIFIED
}

func (x *OrderRequest) GetPrice() *Decimal {
	if x != nil {
		return x.Price
	}
	return nil
}

func (x *OrderRequest) GetQuantity() *Decimal {
	if x != nil {
		return x.Quantity
	}
	return nil
}

func (x *OrderRequest) GetTimeInForce() TimeInForce {
	if x != nil {
		return x.TimeInForce
	}
	return TimeInForce_TIME_IN_FORCE_UNSPECIFIED
}

func (x *OrderRequest) GetMarket() Market {
	if x != nil {
		return x.Market
	}
	return Market_MARKET_UNSPECIFIED
}

func (x *OrderRequest) GetClientOrderId() string {
	if x != nil {
		return x.ClientOrderId
	}
	return ""
}

func (x *OrderRequest) GetStopPrice() *Decimal {
	if x != nil {
		return x.StopPrice
	}
	return nil
}

func (x *OrderRequest) GetReduceOnly() bool {
	if x != nil {
		return x.ReduceOnly
	}
	return false
}

func (x *OrderRequest) GetPostOnly() bool {
	if x != nil {
		return x.PostOnly
	}
	return false
}

func (x *OrderRequest) GetPositionSide() string {
	if x != nil {
		return x.PositionSide
	}
	return ""
}

// OrderResponse for order operations
type OrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderResponse) Reset() {
	*x = OrderResponse{}
	mi := &file_oms_v1_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderResponse) ProtoMessage() {}

func (x *OrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_oms_v1_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderResponse.ProtoReflect.Descriptor instead.
func (*OrderResponse) Descriptor() ([]byte, []int) {
	return file_oms_v1_order_proto_rawDescGZIP(), []int{2}
}

func (x *OrderResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

func (x *OrderResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// CancelOrderRequest for canceling orders
type CancelOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exchange      string                 `protobuf:"bytes,1,opt,name=exchange,proto3" json:"exchange,omitempty"`
	Symbol        string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	OrderId       string                 `protobuf:"bytes,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	ClientOrderId string                 `protobuf:"bytes,4,opt,name=client_order_id,json=clientOrderId,proto3" json:"client_order_id,omitempty"` // Alternative to order_id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderRequest) Reset() {
	*x = CancelOrderRequest{}
	mi := &file_oms_v1_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderRequest) ProtoMessage() {}

func (x *CancelOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oms_v1_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderRequest.ProtoReflect.Descriptor instead.
func (*CancelOrderRequest) Descriptor() ([]byte, []int) {
	return file_oms_v1_order_proto_rawDescGZIP(), []int{3}
}

func (x *CancelOrderRequest) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *CancelOrderRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *CancelOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CancelOrderRequest) GetClientOrderId() string {
	if x != nil {
		return x.ClientOrderId
	}
	return ""
}

// GetOrderRequest for retrieving order details
type GetOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exchange      string                 `protobuf:"bytes,1,opt,name=exchange,proto3" json:"exchange,omitempty"`
	Symbol        string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	OrderId       string                 `protobuf:"bytes,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	ClientOrderId string                 `protobuf:"bytes,4,opt,name=client_order_id,json=clientOrderId,proto3" json:"client_order_id,omitempty"` // Alternative to order_id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderRequest) Reset() {
	*x = GetOrderRequest{}
	mi := &file_oms_v1_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderRequest) ProtoMessage() {}

func (x *GetOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oms_v1_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderRequest.ProtoReflect.Descriptor instead.
func (*GetOrderRequest) Descriptor() ([]byte, []int) {
	return file_oms_v1_order_proto_rawDescGZIP(), []int{4}
}

func (x *GetOrderRequest) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *GetOrderRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *GetOrderRequest) GetClientOrderId() string {
	if x != nil {
		return x.ClientOrderId
	}
	return ""
}

// ListOrdersRequest for listing multiple orders
type ListOrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exchange      string                 `protobuf:"bytes,1,opt,name=exchange,proto3" json:"exchange,omitempty"`
	Symbol        string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Status        OrderStatus            `protobuf:"varint,3,opt,name=status,proto3,enum=oms.v1.OrderStatus" json:"status,omitempty"`
	Market        Market                 `protobuf:"varint,4,opt,name=market,proto3,enum=oms.v1.Market" json:"market,omitempty"`
	Limit         int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	StartTime     *Timestamp             `protobuf:"bytes,6,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *Timestamp             `protobuf:"bytes,7,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersRequest) Reset() {
	*x = ListOrdersRequest{}
	mi := &file_oms_v1_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersRequest) ProtoMessage() {}

func (x *ListOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oms_v1_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersRequest.ProtoReflect.Descriptor instead.
func (*ListOrdersRequest) Descriptor() ([]byte, []int) {
	return file_oms_v1_order_proto_rawDescGZIP(), []int{5}
}

func (x *ListOrdersRequest) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *ListOrdersRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *ListOrdersRequest) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_ORDER_STATUS_UNSPECIFIED
}

func (x *ListOrdersRequest) GetMarket() Market {
	if x != nil {
		return x.Market
	}
	return Market_MARKET_UNSPECIFIED
}

func (x *ListOrdersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListOrdersRequest) GetStartTime() *Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *ListOrdersRequest) GetEndTime() *Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

// ListOrdersResponse contains multiple orders
type ListOrdersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*Order               `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersResponse) Reset() {
	*x = ListOrdersResponse{}
	mi := &file_oms_v1_order_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersResponse) ProtoMessage() {}

func (x *ListOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_oms_v1_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersResponse.ProtoReflect.Descriptor instead.
func (*ListOrdersResponse) Descriptor() ([]byte, []int) {
	return file_oms_v1_order_proto_rawDescGZIP(), []int{6}
}

func (x *ListOrdersResponse) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

func (x *ListOrdersResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_oms_v1_order_proto protoreflect.FileDescriptor

const file_oms_v1_order_proto_rawDesc = "" +
	"\n" +
	"\x12oms/v1/order.proto\x12\x06oms.v1\x1a\x13oms/v1/common.proto\"\xd8\x05\n" +
	"\x05Order\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12&\n" +
	"\x0fclient_order_id\x18\x02 \x01(\tR\rclientOrderId\x12\x1a\n" +
	"\bexchange\x18\x03 \x01(\tR\bexchange\x12\x16\n" +
	"\x06symbol\x18\x04 \x01(\tR\x06symbol\x12%\n" +
	"\x04side\x18\x05 \x01(\x0e2\x11.oms.v1.OrderSideR\x04side\x12%\n" +
	"\x04type\x18\x06 \x01(\x0e2\x11.oms.v1.OrderTypeR\x04type\x12%\n" +
	"\x05price\x18\a \x01(\v2\x0f.oms.v1.DecimalR\x05price\x12+\n" +
	"\bquantity\x18\b \x01(\v2\x0f.oms.v1.DecimalR\bquantity\x12<\n" +
	"\x11executed_quantity\x18\t \x01(\v2\x0f.oms.v1.DecimalR\x10executedQuantity\x12+\n" +
	"\x06status\x18\n" +
	" \x01(\x0e2\x13.oms.v1.OrderStatusR\x06status\x127\n" +
	"\rtime_in_force\x18\v \x01(\x0e2\x13.oms.v1.TimeInForceR\vtimeInForce\x12&\n" +
	"\x06market\x18\f \x01(\x0e2\x0e.oms.v1.MarketR\x06market\x120\n" +
	"\n" +
	"created_at\x18\r \x01(\v2\x11.oms.v1.TimestampR\tcreatedAt\x120\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\v2\x11.oms.v1.TimestampR\tupdatedAt\x12.\n" +
	"\n" +
	"stop_price\x18\x0f \x01(\v2\x0f.oms.v1.DecimalR\tstopPrice\x12\x1f\n" +
	"\vreduce_only\x18\x10 \x01(\bR\n" +
	"reduceOnly\x12\x1b\n" +
	"\tpost_only\x18\x11 \x01(\bR\bpostOnly\x12#\n" +
	"\rposition_side\x18\x12 \x01(\tR\fpositionSide\"\x80\x04\n" +
	"\fOrderRequest\x12\x1a\n" +
	"\bexchange\x18\x01 \x01(\tR\bexchange\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12%\n" +
	"\x04side\x18\x03 \x01(\x0e2\x11.oms.v1.OrderSideR\x04side\x12%\n" +
	"\x04type\x18\x04 \x01(\x0e2\x11.oms.v1.OrderTypeR\x04type\x12%\n" +
	"\x05price\x18\x05 \x01(\v2\x0f.oms.v1.DecimalR\x05price\x12+\n" +
	"\bquantity\x18\x06 \x01(\v2\x0f.oms.v1.DecimalR\bquantity\x127\n" +
	"\rtime_in_force\x18\a \x01(\x0e2\x13.oms.v1.TimeInForceR\vtimeInForce\x12&\n" +
	"\x06market\x18\b \x01(\x0e2\x0e.oms.v1.MarketR\x06market\x12&\n" +
	"\x0fclient_order_id\x18\t \x01(\tR\rclientOrderId\x12.\n" +
	"\n" +
	"stop_price\x18\n" +
	" \x01(\v2\x0f.oms.v1.DecimalR\tstopPrice\x12\x1f\n" +
	"\vreduce_only\x18\v \x01(\bR\n" +
	"reduceOnly\x12\x1b\n" +
	"\tpost_only\x18\f \x01(\bR\bpostOnly\x12#\n" +
	"\rposition_side\x18\r \x01(\tR\fpositionSide\"N\n" +
	"\rOrderResponse\x12#\n" +
	"\x05order\x18\x01 \x01(\v2\r.oms.v1.OrderR\x05order\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x8b\x01\n" +
	"\x12CancelOrderRequest\x12\x1a\n" +
	"\bexchange\x18\x01 \x01(\tR\bexchange\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x19\n" +
	"\border_id\x18\x03 \x01(\tR\aorderId\x12&\n" +
	"\x0fclient_order_id\x18\x04 \x01(\tR\rclientOrderId\"\x88\x01\n" +
	"\x0fGetOrderRequest\x12\x1a\n" +
	"\bexchange\x18\x01 \x01(\tR\bexchange\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x19\n" +
	"\border_id\x18\x03 \x01(\tR\aorderId\x12&\n" +
	"\x0fclient_order_id\x18\x04 \x01(\tR\rclientOrderId\"\x92\x02\n" +
	"\x11ListOrdersRequest\x12\x1a\n" +
	"\bexchange\x18\x01 \x01(\tR\bexchange\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12+\n" +
	"\x06status\x18\x03 \x01(\x0e2\x13.oms.v1.OrderStatusR\x06status\x12&\n" +
	"\x06market\x18\x04 \x01(\x0e2\x0e.oms.v1.MarketR\x06market\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\x120\n" +
	"\n" +
	"start_time\x18\x06 \x01(\v2\x11.oms.v1.TimestampR\tstartTime\x12,\n" +
	"\bend_time\x18\a \x01(\v2\x11.oms.v1.TimestampR\aendTime\"Q\n" +
	"\x12ListOrdersResponse\x12%\n" +
	"\x06orders\x18\x01 \x03(\v2\r.oms.v1.OrderR\x06orders\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05totalB.Z,github.com/mExOms/pkg/proto/oms/v1;omsv1b\x06proto3"

var (
	file_oms_v1_order_proto_rawDescOnce sync.Once
	file_oms_v1_order_proto_rawDescData []byte
)

func file_oms_v1_order_proto_rawDescGZIP() []byte {
	file_oms_v1_order_proto_rawDescOnce.Do(func() {
		file_oms_v1_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_oms_v1_order_proto_rawDesc), len(file_oms_v1_order_proto_rawDesc)))
	})
	return file_oms_v1_order_proto_rawDescData
}

var file_oms_v1_order_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_oms_v1_order_proto_goTypes = []any{
	(*Order)(nil),              // 0: oms.v1.Order
	(*OrderRequest)(nil),       // 1: oms.v1.OrderRequest
	(*OrderResponse)(nil),      // 2: oms.v1.OrderResponse
	(*CancelOrderRequest)(nil), // 3: oms.v1.CancelOrderRequest
	(*GetOrderRequest)(nil),    // 4: oms.v1.GetOrderRequest
	(*ListOrdersRequest)(nil),  // 5: oms.v1.ListOrdersRequest
	(*ListOrdersResponse)(nil), // 6: oms.v1.ListOrdersResponse
	(OrderSide)(0),             // 7: oms.v1.OrderSide
	(OrderType)(0),             // 8: oms.v1.OrderType
	(*Decimal)(nil),            // 9: oms.v1.Decimal
	(OrderStatus)(0),           // 10: oms.v1.OrderStatus
	(TimeInForce)(0),           // 11: oms.v1.TimeInForce
	(Market)(0),                // 12: oms.v1.Market
	(*Timestamp)(nil),          // 13: oms.v1.Timestamp
}
var file_oms_v1_order_proto_depIdxs = []int32{
	7,  // 0: oms.v1.Order.side:type_name -> oms.v1.OrderSide
	8,  // 1: oms.v1.Order.type:type_name -> oms.v1.OrderType
	9,  // 2: oms.v1.Order.price:type_name -> oms.v1.Decimal
	9,  // 3: oms.v1.Order.quantity:type_name -> oms.v1.Decimal
	9,  // 4: oms.v1.Order.executed_quantity:type_name -> oms.v1.Decimal
	10, // 5: oms.v1.Order.status:type_name -> oms.v1.OrderStatus
	11, // 6: oms.v1.Order.time_in_force:type_name -> oms.v1.TimeInForce
	12, // 7: oms.v1.Order.market:type_name -> oms.v1.Market
	13, // 8: oms.v1.Order.created_at:type_name -> oms.v1.Timestamp
	13, // 9: oms.v1.Order.updated_at:type_name -> oms.v1.Timestamp
	9,  // 10: oms.v1.Order.stop_price:type_name -> oms.v1.Decimal
	7,  // 11: oms.v1.OrderRequest.side:type_name -> oms.v1.OrderSide
	8,  // 12: oms.v1.OrderRequest.type:type_name -> oms.v1.OrderType
	9,  // 13: oms.v1.OrderRequest.price:type_name -> oms.v1.Decimal
	9,  // 14: oms.v1.OrderRequest.quantity:type_name -> oms.v1.Decimal
	11, // 15: oms.v1.OrderRequest.time_in_force:type_name -> oms.v1.TimeInForce
	12, // 16: oms.v1.OrderRequest.market:type_name -> oms.v1.Market
	9,  // 17: oms.v1.OrderRequest.stop_price:type_name -> oms.v1.Decimal
	0,  // 18: oms.v1.OrderResponse.order:type_name -> oms.v1.Order
	10, // 19: oms.v1.ListOrdersRequest.status:type_name -> oms.v1.OrderStatus
	12, // 20: oms.v1.ListOrdersRequest.market:type_name -> oms.v1.Market
	13, // 21: oms.v1.ListOrdersRequest.start_time:type_name -> oms.v1.Timestamp
	13, // 22: oms.v1.ListOrdersRequest.end_time:type_name -> oms.v1.Timestamp
	0,  // 23: oms.v1.ListOrdersResponse.orders:type_name -> oms.v1.Order
	24, // [24:24] is the sub-list for method output_type
	24, // [24:24] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_oms_v1_order_proto_init() }
func file_oms_v1_order_proto_init() {
	if File_oms_v1_order_proto != nil {
		return
	}
	file_oms_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_oms_v1_order_proto_rawDesc), len(file_oms_v1_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_oms_v1_order_proto_goTypes,
		DependencyIndexes: file_oms_v1_order_proto_depIdxs,
		MessageInfos:      file_oms_v1_order_proto_msgTypes,
	}.Build()
	File_oms_v1_order_proto = out.File
	file_oms_v1_order_proto_goTypes = nil
	file_oms_v1_order_proto_depIdxs = nil
}
