// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.6.1
// source: oms/v1/position.proto

package omsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Position represents a trading position
type Position struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Exchange      string                 `protobuf:"bytes,2,opt,name=exchange,proto3" json:"exchange,omitempty"`
	Market        Market                 `protobuf:"varint,3,opt,name=market,proto3,enum=oms.v1.Market" json:"market,omitempty"`
	Side          string                 `protobuf:"bytes,4,opt,name=side,proto3" json:"side,omitempty"` // LONG or SHORT
	Quantity      *Decimal               `protobuf:"bytes,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	EntryPrice    *Decimal               `protobuf:"bytes,6,opt,name=entry_price,json=entryPrice,proto3" json:"entry_price,omitempty"`
	MarkPrice     *Decimal               `protobuf:"bytes,7,opt,name=mark_price,json=markPrice,proto3" json:"mark_price,omitempty"`
	UnrealizedPnl *Decimal               `protobuf:"bytes,8,opt,name=unrealized_pnl,json=unrealizedPnl,proto3" json:"unrealized_pnl,omitempty"`
	RealizedPnl   *Decimal               `protobuf:"bytes,9,opt,name=realized_pnl,json=realizedPnl,proto3" json:"realized_pnl,omitempty"`
	Leverage      int32                  `protobuf:"varint,10,opt,name=leverage,proto3" json:"leverage,omitempty"`
	MarginUsed    *Decimal               `protobuf:"bytes,11,opt,name=margin_used,json=marginUsed,proto3" json:"margin_used,omitempty"`
	UpdatedAt     *Timestamp             `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Calculated fields
	PositionValue *Decimal `protobuf:"bytes,13,opt,name=position_value,json=positionValue,proto3" json:"position_value,omitempty"`
	PnlPercent    *Decimal `protobuf:"bytes,14,opt,name=pnl_percent,json=pnlPercent,proto3" json:"pnl_percent,omitempty"`
	MarginRatio   *Decimal `protobuf:"bytes,15,opt,name=margin_ratio,json=marginRatio,proto3" json:"margin_ratio,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Position) Reset() {
	*x = Position{}
	mi := &file_oms_v1_position_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_oms_v1_position_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_oms_v1_position_proto_rawDescGZIP(), []int{0}
}

func (x *Position) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Position) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *Position) GetMarket() Market {
	if x != nil {
		return x.Market
	}
	return Market_MARKET_UNSPECIFIED
}

func (x *Position) GetSide() string {
	if x != nil {
		return x.Side
	}
	return ""
}

func (x *Position) GetQuantity() *Decimal {
	if x != nil {
		return x.Quantity
	}
	return nil
}

func (x *Position) GetEntryPrice() *Decimal {
	if x != nil {
		return x.EntryPrice
	}
	return nil
}

func (x *Position) GetMarkPrice() *Decimal {
	if x != nil {
		return x.MarkPrice
	}
	return nil
}

func (x *Position) GetUnrealizedPnl() *Decimal {
	if x != nil {
		return x.UnrealizedPnl
	}
	return nil
}

func (x *Position) GetRealizedPnl() *Decimal {
	if x != nil {
		return x.RealizedPnl
	}
	return nil
}

func (x *Position) GetLeverage() int32 {
	if x != nil {
		return x.Leverage
	}
	return 0
}

func (x *Position) GetMarginUsed() *Decimal {
	if x != nil {
		return x.MarginUsed
	}
	return nil
}

func (x *Position) GetUpdatedAt() *Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Position) GetPositionValue() *Decimal {
	if x != nil {
		return x.PositionValue
	}
	return nil
}

func (x *Position) GetPnlPercent() *Decimal {
	if x != nil {
		return x.PnlPercent
	}
	return nil
}

func (x *Position) GetMarginRatio() *Decimal {
	if x != nil {
		return x.MarginRatio
	}
	return nil
}

// AggregatedPosition represents positions aggregated across exchanges
type AggregatedPosition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	TotalQuantity *Decimal               `protobuf:"bytes,2,opt,name=total_quantity,json=totalQuantity,proto3" json:"total_quantity,omitempty"`
	AvgEntryPrice *Decimal               `protobuf:"bytes,3,opt,name=avg_entry_price,json=avgEntryPrice,proto3" json:"avg_entry_price,omitempty"`
	TotalValue    *Decimal               `protobuf:"bytes,4,opt,name=total_value,json=totalValue,proto3" json:"total_value,omitempty"`
	TotalPnl      *Decimal               `protobuf:"bytes,5,opt,name=total_pnl,json=totalPnl,proto3" json:"total_pnl,omitempty"`
	Positions     []*Position            `protobuf:"bytes,6,rep,name=positions,proto3" json:"positions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AggregatedPosition) Reset() {
	*x = AggregatedPosition{}
	mi := &file_oms_v1_position_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AggregatedPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggregatedPosition) ProtoMessage() {}

func (x *AggregatedPosition) ProtoReflect() protoreflect.Message {
	mi := &file_oms_v1_position_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggregatedPosition.ProtoReflect.Descriptor instead.
func (*AggregatedPosition) Descriptor() ([]byte, []int) {
	return file_oms_v1_position_proto_rawDescGZIP(), []int{1}
}

func (x *AggregatedPosition) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *AggregatedPosition) GetTotalQuantity() *Decimal {
	if x != nil {
		return x.TotalQuantity
	}
	return nil
}

func (x *AggregatedPosition) GetAvgEntryPrice() *Decimal {
	if x != nil {
		return x.AvgEntryPrice
	}
	return nil
}

func (x *AggregatedPosition) GetTotalValue() *Decimal {
	if x != nil {
		return x.TotalValue
	}
	return nil
}

func (x *AggregatedPosition) GetTotalPnl() *Decimal {
	if x != nil {
		return x.TotalPnl
	}
	return nil
}

func (x *AggregatedPosition) GetPositions() []*Position {
	if x != nil {
		return x.Positions
	}
	return nil
}

// GetPositionRequest for retrieving a specific position
type GetPositionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exchange      string                 `protobuf:"bytes,1,opt,name=exchange,proto3" json:"exchange,omitempty"`
	Symbol        string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPositionRequest) Reset() {
	*x = GetPositionRequest{}
	mi := &file_oms_v1_position_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPositionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPositionRequest) ProtoMessage() {}

func (x *GetPositionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oms_v1_position_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPositionRequest.ProtoReflect.Descriptor instead.
func (*GetPositionRequest) Descriptor() ([]byte, []int) {
	return file_oms_v1_position_proto_rawDescGZIP(), []int{2}
}

func (x *GetPositionRequest) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *GetPositionRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

// GetPositionResponse contains a single position
type GetPositionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Position      *Position              `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPositionResponse) Reset() {
	*x = GetPositionResponse{}
	mi := &file_oms_v1_position_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPositionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPositionResponse) ProtoMessage() {}

func (x *GetPositionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_oms_v1_position_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPositionResponse.ProtoReflect.Descriptor instead.
func (*GetPositionResponse) Descriptor() ([]byte, []int) {
	return file_oms_v1_position_proto_rawDescGZIP(), []int{3}
}

func (x *GetPositionResponse) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

// ListPositionsRequest for listing multiple positions
type ListPositionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exchange      string                 `protobuf:"bytes,1,opt,name=exchange,proto3" json:"exchange,omitempty"`                 // Optional, if empty returns all exchanges
	Market        Market                 `protobuf:"varint,2,opt,name=market,proto3,enum=oms.v1.Market" json:"market,omitempty"` // Optional filter
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPositionsRequest) Reset() {
	*x = ListPositionsRequest{}
	mi := &file_oms_v1_position_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPositionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPositionsRequest) ProtoMessage() {}

func (x *ListPositionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oms_v1_position_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPositionsRequest.ProtoReflect.Descriptor instead.
func (*ListPositionsRequest) Descriptor() ([]byte, []int) {
	return file_oms_v1_position_proto_rawDescGZIP(), []int{4}
}

func (x *ListPositionsRequest) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *ListPositionsRequest) GetMarket() Market {
	if x != nil {
		return x.Market
	}
	return Market_MARKET_UNSPECIFIED
}

// ListPositionsResponse contains multiple positions
type ListPositionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Positions     []*Position            `protobuf:"bytes,1,rep,name=positions,proto3" json:"positions,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPositionsResponse) Reset() {
	*x = ListPositionsResponse{}
	mi := &file_oms_v1_position_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPositionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPositionsResponse) ProtoMessage() {}

func (x *ListPositionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_oms_v1_position_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPositionsResponse.ProtoReflect.Descriptor instead.
func (*ListPositionsResponse) Descriptor() ([]byte, []int) {
	return file_oms_v1_position_proto_rawDescGZIP(), []int{5}
}

func (x *ListPositionsResponse) GetPositions() []*Position {
	if x != nil {
		return x.Positions
	}
	return nil
}

func (x *ListPositionsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// GetAggregatedPositionsRequest for aggregated view
type GetAggregatedPositionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbols       []string               `protobuf:"bytes,1,rep,name=symbols,proto3" json:"symbols,omitempty"` // Optional filter
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAggregatedPositionsRequest) Reset() {
	*x = GetAggregatedPositionsRequest{}
	mi := &file_oms_v1_position_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAggregatedPositionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAggregatedPositionsRequest) ProtoMessage() {}

func (x *GetAggregatedPositionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oms_v1_position_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAggregatedPositionsRequest.ProtoReflect.Descriptor instead.
func (*GetAggregatedPositionsRequest) Descriptor() ([]byte, []int) {
	return file_oms_v1_position_proto_rawDescGZIP(), []int{6}
}

func (x *GetAggregatedPositionsRequest) GetSymbols() []string {
	if x != nil {
		return x.Symbols
	}
	return nil
}

// GetAggregatedPositionsResponse contains aggregated positions
type GetAggregatedPositionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Positions     []*AggregatedPosition  `protobuf:"bytes,1,rep,name=positions,proto3" json:"positions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAggregatedPositionsResponse) Reset() {
	*x = GetAggregatedPositionsResponse{}
	mi := &file_oms_v1_position_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAggregatedPositionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAggregatedPositionsResponse) ProtoMessage() {}

func (x *GetAggregatedPositionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_oms_v1_position_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAggregatedPositionsResponse.ProtoReflect.Descriptor instead.
func (*GetAggregatedPositionsResponse) Descriptor() ([]byte, []int) {
	return file_oms_v1_position_proto_rawDescGZIP(), []int{7}
}

func (x *GetAggregatedPositionsResponse) GetPositions() []*AggregatedPosition {
	if x != nil {
		return x.Positions
	}
	return nil
}

// RiskMetrics contains risk-related metrics
type RiskMetrics struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PositionCount   int32                  `protobuf:"varint,1,opt,name=position_count,json=positionCount,proto3" json:"position_count,omitempty"`
	TotalValue      *Decimal               `protobuf:"bytes,2,opt,name=total_value,json=totalValue,proto3" json:"total_value,omitempty"`
	TotalMarginUsed *Decimal               `protobuf:"bytes,3,opt,name=total_margin_used,json=totalMarginUsed,proto3" json:"total_margin_used,omitempty"`
	MaxLeverage     *Decimal               `protobuf:"bytes,4,opt,name=max_leverage,json=maxLeverage,proto3" json:"max_leverage,omitempty"`
	UnrealizedPnl   *Decimal               `protobuf:"bytes,5,opt,name=unrealized_pnl,json=unrealizedPnl,proto3" json:"unrealized_pnl,omitempty"`
	RealizedPnl     *Decimal               `protobuf:"bytes,6,opt,name=realized_pnl,json=realizedPnl,proto3" json:"realized_pnl,omitempty"`
	TotalPnl        *Decimal               `protobuf:"bytes,7,opt,name=total_pnl,json=totalPnl,proto3" json:"total_pnl,omitempty"`
	UpdatesCount    int64                  `protobuf:"varint,8,opt,name=updates_count,json=updatesCount,proto3" json:"updates_count,omitempty"`
	ReadsCount      int64                  `protobuf:"varint,9,opt,name=reads_count,json=readsCount,proto3" json:"reads_count,omitempty"`
	AvgCalcTimeUs   float64                `protobuf:"fixed64,10,opt,name=avg_calc_time_us,json=avgCalcTimeUs,proto3" json:"avg_calc_time_us,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RiskMetrics) Reset() {
	*x = RiskMetrics{}
	mi := &file_oms_v1_position_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RiskMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiskMetrics) ProtoMessage() {}

func (x *RiskMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_oms_v1_position_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiskMetrics.ProtoReflect.Descriptor instead.
func (*RiskMetrics) Descriptor() ([]byte, []int) {
	return file_oms_v1_position_proto_rawDescGZIP(), []int{8}
}

func (x *RiskMetrics) GetPositionCount() int32 {
	if x != nil {
		return x.PositionCount
	}
	return 0
}

func (x *RiskMetrics) GetTotalValue() *Decimal {
	if x != nil {
		return x.TotalValue
	}
	return nil
}

func (x *RiskMetrics) GetTotalMarginUsed() *Decimal {
	if x != nil {
		return x.TotalMarginUsed
	}
	return nil
}

func (x *RiskMetrics) GetMaxLeverage() *Decimal {
	if x != nil {
		return x.MaxLeverage
	}
	return nil
}

func (x *RiskMetrics) GetUnrealizedPnl() *Decimal {
	if x != nil {
		return x.UnrealizedPnl
	}
	return nil
}

func (x *RiskMetrics) GetRealizedPnl() *Decimal {
	if x != nil {
		return x.RealizedPnl
	}
	return nil
}

func (x *RiskMetrics) GetTotalPnl() *Decimal {
	if x != nil {
		return x.TotalPnl
	}
	return nil
}

func (x *RiskMetrics) GetUpdatesCount() int64 {
	if x != nil {
		return x.UpdatesCount
	}
	return 0
}

func (x *RiskMetrics) GetReadsCount() int64 {
	if x != nil {
		return x.ReadsCount
	}
	return 0
}

func (x *RiskMetrics) GetAvgCalcTimeUs() float64 {
	if x != nil {
		return x.AvgCalcTimeUs
	}
	return 0
}

// GetRiskMetricsRequest for risk metrics
type GetRiskMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRiskMetricsRequest) Reset() {
	*x = GetRiskMetricsRequest{}
	mi := &file_oms_v1_position_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRiskMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRiskMetricsRequest) ProtoMessage() {}

func (x *GetRiskMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oms_v1_position_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRiskMetricsRequest.ProtoReflect.Descriptor instead.
func (*GetRiskMetricsRequest) Descriptor() ([]byte, []int) {
	return file_oms_v1_position_proto_rawDescGZIP(), []int{9}
}

// GetRiskMetricsResponse contains risk metrics
type GetRiskMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       *RiskMetrics           `protobuf:"bytes,1,opt,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRiskMetricsResponse) Reset() {
	*x = GetRiskMetricsResponse{}
	mi := &file_oms_v1_position_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRiskMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRiskMetricsResponse) ProtoMessage() {}

func (x *GetRiskMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_oms_v1_position_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRiskMetricsResponse.ProtoReflect.Descriptor instead.
func (*GetRiskMetricsResponse) Descriptor() ([]byte, []int) {
	return file_oms_v1_position_proto_rawDescGZIP(), []int{10}
}

func (x *GetRiskMetricsResponse) GetMetrics() *RiskMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

var File_oms_v1_position_proto protoreflect.FileDescriptor

const file_oms_v1_position_proto_rawDesc = "" +
	"\n" +
	"\x15oms/v1/position.proto\x12\x06oms.v1\x1a\x13oms/v1/common.proto\"\x93\x05\n" +
	"\bPosition\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x1a\n" +
	"\bexchange\x18\x02 \x01(\tR\bexchange\x12&\n" +
	"\x06market\x18\x03 \x01(\x0e2\x0e.oms.v1.MarketR\x06market\x12\x12\n" +
	"\x04side\x18\x04 \x01(\tR\x04side\x12+\n" +
	"\bquantity\x18\x05 \x01(\v2\x0f.oms.v1.DecimalR\bquantity\x120\n" +
	"\ventry_price\x18\x06 \x01(\v2\x0f.oms.v1.DecimalR\n" +
	"entryPrice\x12.\n" +
	"\n" +
	"mark_price\x18\a \x01(\v2\x0f.oms.v1.DecimalR\tmarkPrice\x126\n" +
	"\x0eunrealized_pnl\x18\b \x01(\v2\x0f.oms.v1.DecimalR\runrealizedPnl\x122\n" +
	"\frealized_pnl\x18\t \x01(\v2\x0f.oms.v1.DecimalR\vrealizedPnl\x12\x1a\n" +
	"\bleverage\x18\n" +
	" \x01(\x05R\bleverage\x120\n" +
	"\vmargin_used\x18\v \x01(\v2\x0f.oms.v1.DecimalR\n" +
	"marginUsed\x120\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x11.oms.v1.TimestampR\tupdatedAt\x126\n" +
	"\x0eposition_value\x18\r \x01(\v2\x0f.oms.v1.DecimalR\rpositionValue\x120\n" +
	"\vpnl_percent\x18\x0e \x01(\v2\x0f.oms.v1.DecimalR\n" +
	"pnlPercent\x122\n" +
	"\fmargin_ratio\x18\x0f \x01(\v2\x0f.oms.v1.DecimalR\vmarginRatio\"\xad\x02\n" +
	"\x12AggregatedPosition\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x126\n" +
	"\x0etotal_quantity\x18\x02 \x01(\v2\x0f.oms.v1.DecimalR\rtotalQuantity\x127\n" +
	"\x0favg_entry_price\x18\x03 \x01(\v2\x0f.oms.v1.DecimalR\ravgEntryPrice\x120\n" +
	"\vtotal_value\x18\x04 \x01(\v2\x0f.oms.v1.DecimalR\n" +
	"totalValue\x12,\n" +
	"\ttotal_pnl\x18\x05 \x01(\v2\x0f.oms.v1.DecimalR\btotalPnl\x12.\n" +
	"\tpositions\x18\x06 \x03(\v2\x10.oms.v1.PositionR\tpositions\"H\n" +
	"\x12GetPositionRequest\x12\x1a\n" +
	"\bexchange\x18\x01 \x01(\tR\bexchange\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\"C\n" +
	"\x13GetPositionResponse\x12,\n" +
	"\bposition\x18\x01 \x01(\v2\x10.oms.v1.PositionR\bposition\"Z\n" +
	"\x14ListPositionsRequest\x12\x1a\n" +
	"\bexchange\x18\x01 \x01(\tR\bexchange\x12&\n" +
	"\x06market\x18\x02 \x01(\x0e2\x0e.oms.v1.MarketR\x06market\"]\n" +
	"\x15ListPositionsResponse\x12.\n" +
	"\tpositions\x18\x01 \x03(\v2\x10.oms.v1.PositionR\tpositions\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"9\n" +
	"\x1dGetAggregatedPositionsRequest\x12\x18\n" +
	"\asymbols\x18\x01 \x03(\tR\asymbols\"Z\n" +
	"\x1eGetAggregatedPositionsResponse\x128\n" +
	"\tpositions\x18\x01 \x03(\v2\x1a.oms.v1.AggregatedPositionR\tpositions\"\xe0\x03\n" +
	"\vRiskMetrics\x12%\n" +
	"\x0eposition_count\x18\x01 \x01(\x05R\rpositionCount\x120\n" +
	"\vtotal_value\x18\x02 \x01(\v2\x0f.oms.v1.DecimalR\n" +
	"totalValue\x12;\n" +
	"\x11total_margin_used\x18\x03 \x01(\v2\x0f.oms.v1.DecimalR\x0ftotalMarginUsed\x122\n" +
	"\fmax_leverage\x18\x04 \x01(\v2\x0f.oms.v1.DecimalR\vmaxLeverage\x126\n" +
	"\x0eunrealized_pnl\x18\x05 \x01(\v2\x0f.oms.v1.DecimalR\runrealizedPnl\x122\n" +
	"\frealized_pnl\x18\x06 \x01(\v2\x0f.oms.v1.DecimalR\vrealizedPnl\x12,\n" +
	"\ttotal_pnl\x18\a \x01(\v2\x0f.oms.v1.DecimalR\btotalPnl\x12#\n" +
	"\rupdates_count\x18\b \x01(\x03R\fupdatesCount\x12\x1f\n" +
	"\vreads_count\x18\t \x01(\x03R\n" +
	"readsCount\x12'\n" +
	"\x10avg_calc_time_us\x18\n" +
	" \x01(\x01R\ravgCalcTimeUs\"\x17\n" +
	"\x15GetRiskMetricsRequest\"G\n" +
	"\x16GetRiskMetricsResponse\x12-\n" +
	"\ametrics\x18\x01 \x01(\v2\x13.oms.v1.RiskMetricsR\ametricsB.Z,github.com/mExOms/oms/pkg/proto/oms/v1;omsv1b\x06proto3"

var (
	file_oms_v1_position_proto_rawDescOnce sync.Once
	file_oms_v1_position_proto_rawDescData []byte
)

func file_oms_v1_position_proto_rawDescGZIP() []byte {
	file_oms_v1_position_proto_rawDescOnce.Do(func() {
		file_oms_v1_position_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_oms_v1_position_proto_rawDesc), len(file_oms_v1_position_proto_rawDesc)))
	})
	return file_oms_v1_position_proto_rawDescData
}

var file_oms_v1_position_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_oms_v1_position_proto_goTypes = []any{
	(*Position)(nil),                       // 0: oms.v1.Position
	(*AggregatedPosition)(nil),             // 1: oms.v1.AggregatedPosition
	(*GetPositionRequest)(nil),             // 2: oms.v1.GetPositionRequest
	(*GetPositionResponse)(nil),            // 3: oms.v1.GetPositionResponse
	(*ListPositionsRequest)(nil),           // 4: oms.v1.ListPositionsRequest
	(*ListPositionsResponse)(nil),          // 5: oms.v1.ListPositionsResponse
	(*GetAggregatedPositionsRequest)(nil),  // 6: oms.v1.GetAggregatedPositionsRequest
	(*GetAggregatedPositionsResponse)(nil), // 7: oms.v1.GetAggregatedPositionsResponse
	(*RiskMetrics)(nil),                    // 8: oms.v1.RiskMetrics
	(*GetRiskMetricsRequest)(nil),          // 9: oms.v1.GetRiskMetricsRequest
	(*GetRiskMetricsResponse)(nil),         // 10: oms.v1.GetRiskMetricsResponse
	(Market)(0),                            // 11: oms.v1.Market
	(*Decimal)(nil),                        // 12: oms.v1.Decimal
	(*Timestamp)(nil),                      // 13: oms.v1.Timestamp
}
var file_oms_v1_position_proto_depIdxs = []int32{
	11, // 0: oms.v1.Position.market:type_name -> oms.v1.Market
	12, // 1: oms.v1.Position.quantity:type_name -> oms.v1.Decimal
	12, // 2: oms.v1.Position.entry_price:type_name -> oms.v1.Decimal
	12, // 3: oms.v1.Position.mark_price:type_name -> oms.v1.Decimal
	12, // 4: oms.v1.Position.unrealized_pnl:type_name -> oms.v1.Decimal
	12, // 5: oms.v1.Position.realized_pnl:type_name -> oms.v1.Decimal
	12, // 6: oms.v1.Position.margin_used:type_name -> oms.v1.Decimal
	13, // 7: oms.v1.Position.updated_at:type_name -> oms.v1.Timestamp
	12, // 8: oms.v1.Position.position_value:type_name -> oms.v1.Decimal
	12, // 9: oms.v1.Position.pnl_percent:type_name -> oms.v1.Decimal
	12, // 10: oms.v1.Position.margin_ratio:type_name -> oms.v1.Decimal
	12, // 11: oms.v1.AggregatedPosition.total_quantity:type_name -> oms.v1.Decimal
	12, // 12: oms.v1.AggregatedPosition.avg_entry_price:type_name -> oms.v1.Decimal
	12, // 13: oms.v1.AggregatedPosition.total_value:type_name -> oms.v1.Decimal
	12, // 14: oms.v1.AggregatedPosition.total_pnl:type_name -> oms.v1.Decimal
	0,  // 15: oms.v1.AggregatedPosition.positions:type_name -> oms.v1.Position
	0,  // 16: oms.v1.GetPositionResponse.position:type_name -> oms.v1.Position
	11, // 17: oms.v1.ListPositionsRequest.market:type_name -> oms.v1.Market
	0,  // 18: oms.v1.ListPositionsResponse.positions:type_name -> oms.v1.Position
	1,  // 19: oms.v1.GetAggregatedPositionsResponse.positions:type_name -> oms.v1.AggregatedPosition
	12, // 20: oms.v1.RiskMetrics.total_value:type_name -> oms.v1.Decimal
	12, // 21: oms.v1.RiskMetrics.total_margin_used:type_name -> oms.v1.Decimal
	12, // 22: oms.v1.RiskMetrics.max_leverage:type_name -> oms.v1.Decimal
	12, // 23: oms.v1.RiskMetrics.unrealized_pnl:type_name -> oms.v1.Decimal
	12, // 24: oms.v1.RiskMetrics.realized_pnl:type_name -> oms.v1.Decimal
	12, // 25: oms.v1.RiskMetrics.total_pnl:type_name -> oms.v1.Decimal
	8,  // 26: oms.v1.GetRiskMetricsResponse.metrics:type_name -> oms.v1.RiskMetrics
	27, // [27:27] is the sub-list for method output_type
	27, // [27:27] is the sub-list for method input_type
	27, // [27:27] is the sub-list for extension type_name
	27, // [27:27] is the sub-list for extension extendee
	0,  // [0:27] is the sub-list for field type_name
}

func init() { file_oms_v1_position_proto_init() }
func file_oms_v1_position_proto_init() {
	if File_oms_v1_position_proto != nil {
		return
	}
	file_oms_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_oms_v1_position_proto_rawDesc), len(file_oms_v1_position_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_oms_v1_position_proto_goTypes,
		DependencyIndexes: file_oms_v1_position_proto_depIdxs,
		MessageInfos:      file_oms_v1_position_proto_msgTypes,
	}.Build()
	File_oms_v1_position_proto = out.File
	file_oms_v1_position_proto_goTypes = nil
	file_oms_v1_position_proto_depIdxs = nil
}
