// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.6.1
// source: oms/v1/service.proto

package omsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_oms_v1_service_proto protoreflect.FileDescriptor

const file_oms_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x14oms/v1/service.proto\x12\x06oms.v1\x1a\x12oms/v1/order.proto\x1a\x15oms/v1/position.proto\x1a\x18oms/v1/market_data.proto\x1a\x11oms/v1/auth.proto2\x8d\x02\n" +
	"\fOrderService\x12:\n" +
	"\vCreateOrder\x12\x14.oms.v1.OrderRequest\x1a\x15.oms.v1.OrderResponse\x12@\n" +
	"\vCancelOrder\x12\x1a.oms.v1.CancelOrderRequest\x1a\x15.oms.v1.OrderResponse\x12:\n" +
	"\bGetOrder\x12\x17.oms.v1.GetOrderRequest\x1a\x15.oms.v1.OrderResponse\x12C\n" +
	"\n" +
	"ListOrders\x12\x19.oms.v1.ListOrdersRequest\x1a\x1a.oms.v1.ListOrdersResponse2\xe1\x02\n" +
	"\x0fPositionService\x12F\n" +
	"\vGetPosition\x12\x1a.oms.v1.GetPositionRequest\x1a\x1b.oms.v1.GetPositionResponse\x12L\n" +
	"\rListPositions\x12\x1c.oms.v1.ListPositionsRequest\x1a\x1d.oms.v1.ListPositionsResponse\x12g\n" +
	"\x16GetAggregatedPositions\x12%.oms.v1.GetAggregatedPositionsRequest\x1a&.oms.v1.GetAggregatedPositionsResponse\x12O\n" +
	"\x0eGetRiskMetrics\x12\x1d.oms.v1.GetRiskMetricsRequest\x1a\x1e.oms.v1.GetRiskMetricsResponse2\xe3\x02\n" +
	"\x11MarketDataService\x12>\n" +
	"\fGetOrderBook\x12\x1b.oms.v1.GetOrderBookRequest\x1a\x11.oms.v1.OrderBook\x125\n" +
	"\tGetTicker\x12\x18.oms.v1.GetTickerRequest\x1a\x0e.oms.v1.Ticker\x12R\n" +
	"\x0fGetRecentTrades\x12\x1e.oms.v1.GetRecentTradesRequest\x1a\x1f.oms.v1.GetRecentTradesResponse\x12@\n" +
	"\tGetKlines\x12\x18.oms.v1.GetKlinesRequest\x1a\x19.oms.v1.GetKlinesResponse\x12A\n" +
	"\tSubscribe\x12\x18.oms.v1.SubscribeRequest\x1a\x18.oms.v1.MarketDataUpdate0\x012\xf1\x02\n" +
	"\vAuthService\x129\n" +
	"\fAuthenticate\x12\x13.oms.v1.AuthRequest\x1a\x14.oms.v1.AuthResponse\x12I\n" +
	"\fRefreshToken\x12\x1b.oms.v1.RefreshTokenRequest\x1a\x1c.oms.v1.RefreshTokenResponse\x12I\n" +
	"\fCreateAPIKey\x12\x1b.oms.v1.CreateAPIKeyRequest\x1a\x1c.oms.v1.CreateAPIKeyResponse\x12F\n" +
	"\vListAPIKeys\x12\x1a.oms.v1.ListAPIKeysRequest\x1a\x1b.oms.v1.ListAPIKeysResponse\x12I\n" +
	"\fRevokeAPIKey\x12\x1b.oms.v1.RevokeAPIKeyRequest\x1a\x1c.oms.v1.RevokeAPIKeyResponseB.Z,github.com/mExOms/oms/pkg/proto/oms/v1;omsv1b\x06proto3"

var file_oms_v1_service_proto_goTypes = []any{
	(*OrderRequest)(nil),                   // 0: oms.v1.OrderRequest
	(*CancelOrderRequest)(nil),             // 1: oms.v1.CancelOrderRequest
	(*GetOrderRequest)(nil),                // 2: oms.v1.GetOrderRequest
	(*ListOrdersRequest)(nil),              // 3: oms.v1.ListOrdersRequest
	(*GetPositionRequest)(nil),             // 4: oms.v1.GetPositionRequest
	(*ListPositionsRequest)(nil),           // 5: oms.v1.ListPositionsRequest
	(*GetAggregatedPositionsRequest)(nil),  // 6: oms.v1.GetAggregatedPositionsRequest
	(*GetRiskMetricsRequest)(nil),          // 7: oms.v1.GetRiskMetricsRequest
	(*GetOrderBookRequest)(nil),            // 8: oms.v1.GetOrderBookRequest
	(*GetTickerRequest)(nil),               // 9: oms.v1.GetTickerRequest
	(*GetRecentTradesRequest)(nil),         // 10: oms.v1.GetRecentTradesRequest
	(*GetKlinesRequest)(nil),               // 11: oms.v1.GetKlinesRequest
	(*SubscribeRequest)(nil),               // 12: oms.v1.SubscribeRequest
	(*AuthRequest)(nil),                    // 13: oms.v1.AuthRequest
	(*RefreshTokenRequest)(nil),            // 14: oms.v1.RefreshTokenRequest
	(*CreateAPIKeyRequest)(nil),            // 15: oms.v1.CreateAPIKeyRequest
	(*ListAPIKeysRequest)(nil),             // 16: oms.v1.ListAPIKeysRequest
	(*RevokeAPIKeyRequest)(nil),            // 17: oms.v1.RevokeAPIKeyRequest
	(*OrderResponse)(nil),                  // 18: oms.v1.OrderResponse
	(*ListOrdersResponse)(nil),             // 19: oms.v1.ListOrdersResponse
	(*GetPositionResponse)(nil),            // 20: oms.v1.GetPositionResponse
	(*ListPositionsResponse)(nil),          // 21: oms.v1.ListPositionsResponse
	(*GetAggregatedPositionsResponse)(nil), // 22: oms.v1.GetAggregatedPositionsResponse
	(*GetRiskMetricsResponse)(nil),         // 23: oms.v1.GetRiskMetricsResponse
	(*OrderBook)(nil),                      // 24: oms.v1.OrderBook
	(*Ticker)(nil),                         // 25: oms.v1.Ticker
	(*GetRecentTradesResponse)(nil),        // 26: oms.v1.GetRecentTradesResponse
	(*GetKlinesResponse)(nil),              // 27: oms.v1.GetKlinesResponse
	(*MarketDataUpdate)(nil),               // 28: oms.v1.MarketDataUpdate
	(*AuthResponse)(nil),                   // 29: oms.v1.AuthResponse
	(*RefreshTokenResponse)(nil),           // 30: oms.v1.RefreshTokenResponse
	(*CreateAPIKeyResponse)(nil),           // 31: oms.v1.CreateAPIKeyResponse
	(*ListAPIKeysResponse)(nil),            // 32: oms.v1.ListAPIKeysResponse
	(*RevokeAPIKeyResponse)(nil),           // 33: oms.v1.RevokeAPIKeyResponse
}
var file_oms_v1_service_proto_depIdxs = []int32{
	0,  // 0: oms.v1.OrderService.CreateOrder:input_type -> oms.v1.OrderRequest
	1,  // 1: oms.v1.OrderService.CancelOrder:input_type -> oms.v1.CancelOrderRequest
	2,  // 2: oms.v1.OrderService.GetOrder:input_type -> oms.v1.GetOrderRequest
	3,  // 3: oms.v1.OrderService.ListOrders:input_type -> oms.v1.ListOrdersRequest
	4,  // 4: oms.v1.PositionService.GetPosition:input_type -> oms.v1.GetPositionRequest
	5,  // 5: oms.v1.PositionService.ListPositions:input_type -> oms.v1.ListPositionsRequest
	6,  // 6: oms.v1.PositionService.GetAggregatedPositions:input_type -> oms.v1.GetAggregatedPositionsRequest
	7,  // 7: oms.v1.PositionService.GetRiskMetrics:input_type -> oms.v1.GetRiskMetricsRequest
	8,  // 8: oms.v1.MarketDataService.GetOrderBook:input_type -> oms.v1.GetOrderBookRequest
	9,  // 9: oms.v1.MarketDataService.GetTicker:input_type -> oms.v1.GetTickerRequest
	10, // 10: oms.v1.MarketDataService.GetRecentTrades:input_type -> oms.v1.GetRecentTradesRequest
	11, // 11: oms.v1.MarketDataService.GetKlines:input_type -> oms.v1.GetKlinesRequest
	12, // 12: oms.v1.MarketDataService.Subscribe:input_type -> oms.v1.SubscribeRequest
	13, // 13: oms.v1.AuthService.Authenticate:input_type -> oms.v1.AuthRequest
	14, // 14: oms.v1.AuthService.RefreshToken:input_type -> oms.v1.RefreshTokenRequest
	15, // 15: oms.v1.AuthService.CreateAPIKey:input_type -> oms.v1.CreateAPIKeyRequest
	16, // 16: oms.v1.AuthService.ListAPIKeys:input_type -> oms.v1.ListAPIKeysRequest
	17, // 17: oms.v1.AuthService.RevokeAPIKey:input_type -> oms.v1.RevokeAPIKeyRequest
	18, // 18: oms.v1.OrderService.CreateOrder:output_type -> oms.v1.OrderResponse
	18, // 19: oms.v1.OrderService.CancelOrder:output_type -> oms.v1.OrderResponse
	18, // 20: oms.v1.OrderService.GetOrder:output_type -> oms.v1.OrderResponse
	19, // 21: oms.v1.OrderService.ListOrders:output_type -> oms.v1.ListOrdersResponse
	20, // 22: oms.v1.PositionService.GetPosition:output_type -> oms.v1.GetPositionResponse
	21, // 23: oms.v1.PositionService.ListPositions:output_type -> oms.v1.ListPositionsResponse
	22, // 24: oms.v1.PositionService.GetAggregatedPositions:output_type -> oms.v1.GetAggregatedPositionsResponse
	23, // 25: oms.v1.PositionService.GetRiskMetrics:output_type -> oms.v1.GetRiskMetricsResponse
	24, // 26: oms.v1.MarketDataService.GetOrderBook:output_type -> oms.v1.OrderBook
	25, // 27: oms.v1.MarketDataService.GetTicker:output_type -> oms.v1.Ticker
	26, // 28: oms.v1.MarketDataService.GetRecentTrades:output_type -> oms.v1.GetRecentTradesResponse
	27, // 29: oms.v1.MarketDataService.GetKlines:output_type -> oms.v1.GetKlinesResponse
	28, // 30: oms.v1.MarketDataService.Subscribe:output_type -> oms.v1.MarketDataUpdate
	29, // 31: oms.v1.AuthService.Authenticate:output_type -> oms.v1.AuthResponse
	30, // 32: oms.v1.AuthService.RefreshToken:output_type -> oms.v1.RefreshTokenResponse
	31, // 33: oms.v1.AuthService.CreateAPIKey:output_type -> oms.v1.CreateAPIKeyResponse
	32, // 34: oms.v1.AuthService.ListAPIKeys:output_type -> oms.v1.ListAPIKeysResponse
	33, // 35: oms.v1.AuthService.RevokeAPIKey:output_type -> oms.v1.RevokeAPIKeyResponse
	18, // [18:36] is the sub-list for method output_type
	0,  // [0:18] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_oms_v1_service_proto_init() }
func file_oms_v1_service_proto_init() {
	if File_oms_v1_service_proto != nil {
		return
	}
	file_oms_v1_order_proto_init()
	file_oms_v1_position_proto_init()
	file_oms_v1_market_data_proto_init()
	file_oms_v1_auth_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_oms_v1_service_proto_rawDesc), len(file_oms_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_oms_v1_service_proto_goTypes,
		DependencyIndexes: file_oms_v1_service_proto_depIdxs,
	}.Build()
	File_oms_v1_service_proto = out.File
	file_oms_v1_service_proto_goTypes = nil
	file_oms_v1_service_proto_depIdxs = nil
}
