# Multi-Exchange OMS Configuration

# System Configuration
system:
  environment: development
  log_level: info
  
# Core Engine Configuration  
core:
  cpu_affinity: true
  performance_mode: high
  
# Risk Management
risk:
  max_position_value: 1000000.0  # $1M
  max_order_value: 100000.0      # $100k
  daily_loss_limit: 50000.0      # $50k
  max_open_orders: 100
  max_leverage: 10.0

# Arbitrage Configuration
arbitrage:
  min_profit_rate: 0.001         # 0.1%
  min_profit_amount: 10.0        # $10
  max_position_size: 100000.0    # $100k
  opportunity_ttl_ms: 500        # 500ms

# Market Maker Configuration
market_maker:
  base_spread_bps: 10            # 0.1%
  min_spread_bps: 5              # 0.05%
  max_spread_bps: 50             # 0.5%
  quote_size: 0.1                # 0.1 BTC
  quote_levels: 3
  max_inventory: 1.0             # 1 BTC

# Exchange Configuration
exchanges:
  binance:
    spot:
      enabled: true
      test_mode: true
      rate_limit: 1200           # requests per minute
    futures:
      enabled: true
      test_mode: true
      default_leverage: 10
      
# gRPC Configuration      
grpc:
  port: 50051
  max_concurrent_streams: 1000
  keepalive_time_sec: 5
  
# NATS Configuration (when available)
nats:
  enabled: false
  url: nats://localhost:4222
  
# Monitoring
monitoring:
  metrics_port: 9090
  health_check_interval_sec: 10