# Multi-Exchange OMS Strategy Configuration

strategies:
  # Arbitrage Strategy Configuration
  arbitrage:
    enabled: true
    pairs:
      - symbol: BTC/USDT
        exchanges: [binance, upbit, bybit]
        min_profit_rate: 0.001  # 0.1%
        max_position: 10000      # $10,000
        
      - symbol: ETH/USDT
        exchanges: [binance, okx]
        min_profit_rate: 0.0015
        max_position: 5000
        
    execution:
      mode: aggressive  # aggressive, passive, hybrid
      timeout: 500ms
      retry: 3
      
    accounts:
      binance: sub_spot_arb
      upbit: sub_arb
      bybit: sub_arb
      
  # Market Making Strategy Configuration
  market_making:
    enabled: true
    instruments:
      - symbol: BTC/USDT
        exchange: binance
        account: sub_market_making
        spread_bps: 10      # 0.1%
        quote_size: 0.1     # 0.1 BTC
        max_inventory: 1.0  # 1 BTC
        refresh_rate: 1s
        quote_levels: 3
        level_spacing_bps: 2
        
      - symbol: ETH/USDT
        exchange: binance
        account: sub_market_making
        spread_bps: 15
        quote_size: 1.0
        max_inventory: 10.0
        refresh_rate: 2s
        quote_levels: 3
        level_spacing_bps: 3
        
    risk_limits:
      max_daily_loss: 1000  # $1,000
      max_position_value: 50000
      auto_stop_loss: 0.02  # 2%
      
    market_conditions:
      volatility_factor: 1.0
      inventory_skew: 0.5
      min_spread_bps: 5
      max_spread_bps: 50
      
  # Kill Switch Configuration (Global)
  kill_switch:
    max_daily_loss: 5000
    max_consecutive_losses: 10
    emergency_contacts:
      - slack: "#trading-alerts"
      - email: "trader@example.com"
    
    # Per-strategy kill switches
    strategy_limits:
      arbitrage:
        max_daily_loss: 2000
        max_failed_trades: 20
        
      market_making:
        max_daily_loss: 3000
        max_inventory_breach: 5  # Number of times inventory limit is hit
        
# Strategy Scheduling
scheduling:
  arbitrage:
    active_hours:
      - start: "00:00"
        end: "23:59"
        days: [mon, tue, wed, thu, fri, sat, sun]
        
  market_making:
    active_hours:
      - start: "08:00"
        end: "20:00"
        days: [mon, tue, wed, thu, fri]
      - start: "10:00"
        end: "16:00"
        days: [sat, sun]
        
# Performance Targets
performance_targets:
  arbitrage:
    min_daily_trades: 10
    target_daily_profit: 100  # $100
    max_slippage: 0.0005     # 0.05%
    
  market_making:
    target_spread_capture: 0.7  # Capture 70% of spread
    min_fill_rate: 0.3         # 30% of quotes should fill
    target_daily_volume: 100000 # $100k volume
    
# Monitoring and Alerts
monitoring:
  metrics_interval: 10s
  
  alerts:
    - type: position_limit
      threshold: 0.9  # Alert at 90% of max position
      channels: [slack, email]
      
    - type: daily_loss
      threshold: 0.8  # Alert at 80% of max daily loss
      channels: [slack, email]
      
    - type: spread_deviation
      threshold: 2.0  # Alert if spread is 2x normal
      channels: [slack]
      
    - type: inventory_skew
      threshold: 0.8  # Alert at 80% inventory utilization
      channels: [slack]
      
# Backtesting Configuration
backtesting:
  data_source: /data/historical
  
  scenarios:
    - name: high_volatility
      volatility_multiplier: 2.0
      duration: 7d
      
    - name: trending_market
      trend_strength: 0.02  # 2% daily trend
      duration: 30d
      
    - name: flash_crash
      crash_magnitude: 0.1  # 10% drop
      recovery_time: 1h
      
  metrics:
    - sharpe_ratio
    - max_drawdown
    - win_rate
    - profit_factor
    - average_trade_duration